FROM node:20-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./

RUN npm install

# Копирование исходников
COPY . .

# Порт Vite
EXPOSE 5173

# Запуск dev сервера
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


